name: theartoftravel
favicon: null
layout_spectrum: 0.76335
typography_spectrum: 0.73619
title: The Art of Travel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e5e5'
    - '#363636'
    - '#181818'
    - '#606060'
    - '#a8a8a8'
  brandStrength: 0.5
  lightness: 0.6014748809393495
  saturation: 1
  rhythmicContrast: 1
purpose: []
